// Auto-generated by scripts/update-addresses.js; do not edit manually.
export const CONTRACT_ADDRESSES = {
  31337: {
    AssetNFT: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
    AssetRegistry: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
    Fractionalizer: "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9",
    LicenseNFT: "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9",
    LicenseManager: "0x5fc8d32690cc91d4c39d9d3abcbd16989f875707",
    SecondaryMarket: "0xa513e6e4b8f2a923d98304ec87f64353c4d5c853",
  },
  // Add other chains (e.g., Sepolia 11155111) manually or by extending this script.
} as const;

export type SupportedChainId = keyof typeof CONTRACT_ADDRESSES;

export function getContractAddress(
  chainId: number,
  contract: keyof (typeof CONTRACT_ADDRESSES)[31337]
): `0x${string}` | undefined {
  const addresses = CONTRACT_ADDRESSES[chainId as SupportedChainId];
  if (!addresses) return undefined;
  const addr = addresses[contract];
  return addr ? (addr as `0x${string}`) : undefined;
}
