// Auto-generated by scripts/update-addresses.js; do not edit manually.
export const CONTRACT_ADDRESSES = {
  // Local Foundry/Anvil
  31337: {
    AssetNFT: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
    AssetRegistry: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
    Fractionalizer: "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9",
    LicenseNFT: "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9",
    LicenseManager: "0x5fc8d32690cc91d4c39d9d3abcbd16989f875707",
    SecondaryMarket: "0xa513e6e4b8f2a923d98304ec87f64353c4d5c853",
    OrderBook: "0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6",
  },
  // Story Protocol Aeneid Testnet (Chain ID: 1315)
  1315: {
    AssetNFT: "0x832eBb3063499843070FA2C41a35c195fa38162D",
    AssetRegistry: "0xb744cec7EfA685301Cc24EAFfdC2a0B4975e5B30",
    Fractionalizer: "0x14E1cf8434e18b573db7Ccfa66f0623de24b3D62",
    LicenseNFT: "0x9Ada21D367DcaF8C4a4f63e14C69F19d5b94A344",
    LicenseManager: "0xd9167b9F4faCE06298c0E84Deb35868DbaDb735f",
    SecondaryMarket: "0xf477FEcF885956eeCe8E84a1507D7b5Ef3Fae589",
    OrderBook: "0x7AEE1BFE9fD152eA1f99818cB02E1bc64DBE8b7C",
  },
} as const;

export type SupportedChainId = keyof typeof CONTRACT_ADDRESSES;

export function getContractAddress(
  chainId: number,
  contract: keyof (typeof CONTRACT_ADDRESSES)[31337]
): `0x${string}` | undefined {
  const addresses = CONTRACT_ADDRESSES[chainId as SupportedChainId];
  if (!addresses) return undefined;
  const addr = addresses[contract];
  return addr ? (addr as `0x${string}`) : undefined;
}
