// Auto-generated by scripts/update-addresses.js; do not edit manually.
export const CONTRACT_ADDRESSES = {
  // Local Foundry/Anvil
  31337: {
    AssetNFT: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
    AssetRegistry: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
    Fractionalizer: "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9",
    LicenseNFT: "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9",
    LicenseManager: "0x5fc8d32690cc91d4c39d9d3abcbd16989f875707",
    SecondaryMarket: "0xa513e6e4b8f2a923d98304ec87f64353c4d5c853",
    OrderBook: "0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6",
  },
  // Story Protocol Aeneid Testnet (Chain ID: 1315)
  1315: {
    AssetNFT: "0x2507676D4c1d9a8d18666145BA47D1799E799fc7",
    AssetRegistry: "0x761f146145bC86B173ad4EB102Cb046589026434",
    Fractionalizer: "0xE7B7d57dbAdAB7C5e34A875e4399c5ce6bCe158D",
    LicenseNFT: "0x8169d2Af661c0642702caf06DB3e53d53Ba81D64",
    LicenseManager: "0xBDf8BffD37EF5F6246870cD8c1Fe0E626FA2405f",
    SecondaryMarket: "0xc0dBc3F43A94411147CbA01471125bf31c3B1D70",
    OrderBook: "0x08eF968108A4Eaca911D0781b13360c370359fa2",
  },
} as const;

export type SupportedChainId = keyof typeof CONTRACT_ADDRESSES;

export function getContractAddress(
  chainId: number,
  contract: keyof (typeof CONTRACT_ADDRESSES)[31337]
): `0x${string}` | undefined {
  const addresses = CONTRACT_ADDRESSES[chainId as SupportedChainId];
  if (!addresses) return undefined;
  const addr = addresses[contract];
  return addr ? (addr as `0x${string}`) : undefined;
}
